.PHONY: clean All

All:
	@echo "----------Building project:[ CppTest - Debug ]----------"
	@cd "CppTest" && "$(MAKE)" -f  "CppTest.mk"
clean:
	@echo "----------Cleaning project:[ CppTest - Debug ]----------"
	@cd "CppTest" && "$(MAKE)" -f  "CppTest.mk" clean
